name: Hakaton Team 14 Workflow (main)

on:
  push:
    branches:
      - main

jobs:

  build_and_push_frontend_image:
    name: Build frontend image and push to the DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Clone project to runner
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push frontend image to the Dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: True
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hakaton_14_frontend:latest

  deploy_on_server:
    name: Deploy project on server
    needs: build_and_push_frontend_image
    runs-on: ubuntu-latest
    steps:
      - name: Clone project to runner
        uses: actions/checkout@v3
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd hakaton
            sudo docker compose -f docker-compose.production.yml down
            sudo docker image rm thesuncatcher222/hakaton_14_frontend
            sudo docker image rm thesuncatcher222/hakaton_14_gateway
            sudo docker volume rm hakaton_static_volume
            sudo docker volume prune --force
            sudo docker compose -f docker-compose.production.yml up -d --build
            sudo service nginx restart
  
  send_message_telegram:
    name: Send message to telegram
    needs: deploy_on_server
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ME_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: Деплой "frontend" выполнен успешно!
